"""
agents/srao_agent.py  —  SRAO Agent Definition  ·  google-adk 2.4.0
=====================================================================
Exposes explicit, flat-parameter functional tools to the LlmAgent definition.
Bridges Vertex ADK tool invocation schemas safely to core service classes.
"""

import os
from google.adk.agents import LlmAgent

# SRAO: Import core business engine classes
from tools.rag_retriever import RagRetriever
from tools.code_modernizer import modernize_code_snippet
from tools.pr_creator import validate_diff

from dotenv import load_dotenv
load_dotenv()

# Initialize core services once globally to optimize runtime execution loops
retriever_instance = RagRetriever()

# ── Flattened Bridge Helpers for ADK Agent Registration ──────────────────────

def agent_retrieve_java_docs(pattern_id: str) -> str:
    """
    Retrieve Java 17/21 documentation and migration code recipe blueprints for a pattern.
    
    Args:
        pattern_id: The specific SRAO pattern identifier token (e.g., 'FOR_LOOP', 'RAW_THREAD').
    """
    return retriever_instance.get_migration_recipe(pattern_id=pattern_id)


def agent_modernize_code_snippet(
    file_path: str,
    pattern_id: str,
    description: str,
    target_java: str,
    rag_context: str,
    legacy_code: str # ── NEW SRAO FIX: Accept the code directly from the LLM context
) -> dict:
    """
    Generate modernized Java source code for a specific file and architectural pattern match.
    
    Args:
        file_path: Relative or absolute path targeting the Java source file on disk.
        pattern_id: SRAO pattern identifier token (e.g., 'POJO_CLASS', 'STRING_BUFFER').
        description: Informational statement outlining the modernization objective.
        target_java: The target Java baseline specification version (e.g., 'Java 17', 'Java 21').
        rag_context: Valid migration recipes or structural documentation blocks fetched from RAG.
        legacy_code: The original legacy Java code source string passed directly from agent context memory.
    """
    # Forward the live legacy_code string straight to the modernizer tool
    return modernize_code_snippet(
        file_path=file_path,
        description=description,
        target_java=target_java,
        legacy_code=legacy_code, # Enforces memory passing instead of container disk lookups
        pattern_id=pattern_id,
        rag_context=rag_context
    )


def agent_validate_diff(file_path: str, modernised_code: str) -> dict:
    """
    Execute syntax and structure validation checks on generated code modifications.
    
    Args:
        file_path: The workspace file path targeting the original legacy source asset.
        modernised_code: The complete, updated Java class content string generated by the AI model.
    """
    return validate_diff(
        original_code="",  # Bypassed to allow internal disk loading sequence
        modernised_code=modernised_code,
        file_path=file_path
    )


# ── Strict Multi-Agent Architectural Instruction Profile ─────────────────────

INSTRUCTION = """You are SRAO (Service Refactoring and Optimization Agent), an expert enterprise Java modernization architect.
Your job is to read batch assignments and systematically transform legacy source configurations into clean, production-ready Java 17/21 architectures.

You receive a pre-computed JSON block list detailing legacy Java architectural findings across several workspace targets.

For EACH file and matching pattern element listed in the request payload, execute these sequential orchestration processing updates:

STEP 1: Document Lookup Initialization
Call 'agent_retrieve_java_docs' passing the unique 'pattern_id' parameter. Save this reference text as your modernization context.

STEP 2: Automated Refactoring Generation
Call 'agent_modernize_code_snippet' with these parameters:
  - file_path: The file path provided in the payload block.
  - pattern_id: The pattern identifier token.
  - description: The text description string.
  - target_java: The target Java runtime parameter.
  - rag_context: The precise markdown instruction recipe text returned from STEP 1.
  - legacy_code: The COMPLETE source text of the file you are currently modernizing. Do not truncate it.


CRITICAL OPERATIONAL CONSTRAINTS FOR STEP 2:
  - The tool reads file content directly from 'file_path'. Do not attempt to guess or pass arbitrary snippet content strings.
  - Produce a structured result payload. Never generate Python scripts, mock console logging, or structural execution wrappers.

STEP 3: Structural Modification Validation
Call 'agent_validate_diff' with these parameters:
  - file_path: The target path parameter.
  - modernised_code: The exact string block contained inside the 'modernised_code' response parameter generated during STEP 2.

CRITICAL OPERATIONAL CONSTRAINTS FOR STEP 3:
  - If the tool responds with status 'invalid', pass the diagnostic error message directly into a corrective loop turn by re-calling 'agent_modernize_code_snippet'.
  - Do not execute recursive retry adjustments on results that return a status 'valid' configuration footprint.

STEP 4: Execution Status Reporting Summarization
Once all processing steps complete for the current batch assignment, emit a plain text processing overview summary outlining translation metrics.

DO NOT INVOLVE SEPARATE PIPELINE SUB-TASKS OUTSIDE THOSE DELIBERATELY REGISTERED HERE:
  - Never attempt to open Git Pull Requests or generate telemetry files ('create_pull_request', 'save_changes_locally', 'generate_report'). These operations are managed at the multi-agent system coordinator boundary layer.

PROCESSING SEVERITY PRIORITY TRACK ROUTING RULES:
  - You must iterate over and address high severity patterns ('HIGH') before applying changes to 'MEDIUM' or 'LOW' risk profile items. Do not truncate execution loops early.

── AUTHORIZED SYSTEM COMPLIANCE OVERRIDES ──
  - You have FULL PERMISSION to refactor code inside 'synchronized' blocks and synchronized methods.
  - Replacing a local method 'StringBuffer' variable with a 'StringBuilder' is explicitly safe and does NOT violate synchronization boundaries.
  - Flattening legacy loops/iterators into native Java Streams inside a synchronized block is completely safe and authorized. Do not skip these patterns.
"""

# ── Instantiate Consolidated ADK Agent Runtime Definition ───────────────────

srao_agent = LlmAgent(
    model="gemini-2.5-flash",
    name="srao_agent",
    description="Java modernisation agent leveraging isolated tool pipelines.",
    instruction=INSTRUCTION,
    tools=[
        agent_retrieve_java_docs,
        agent_modernize_code_snippet,
        agent_validate_diff,
    ],
)
