"""
tools/pr_creator.py
────────────────────
Creates a GitHub Pull Request with the modernised Java code changes.
Also provides diff validation using the GitHub API.
"""

import logging
import os
import subprocess
import tempfile
from pathlib import Path
from typing import Optional

import requests

logger = logging.getLogger(__name__)

GITHUB_TOKEN   = os.environ.get("GITHUB_TOKEN", "")
GITHUB_API_URL = "https://api.github.com"

PR_TITLE_TEMPLATE = "[SRAO] Java Modernization: {file_count} file(s) refactored to Java 17/21"
PR_BODY_TEMPLATE  = """
## 🤖 AI-Powered Java Modernization (SRAO Agent)

This Pull Request was automatically generated by the **SRAO Agent** running on
Google Cloud Vertex AI.

### Summary
- **Files modified:** {file_count}
- **Patterns addressed:** {pattern_list}
- **Target Java version:** Java 17/21

### Changes
{change_details}

### How to review
1. Check each file diff for correctness
2. Run `mvn test` / `gradle test` to validate compilation and tests
3. Review the inline `// SRAO:` comments for explanations

### Generated by
- Model: Gemini 2.0 Flash (Vertex AI)
- Agent: SRAO v1.0
- Project: {project_id}
"""


def validate_diff(original_code: str, modernised_code: str) -> dict:
    """
    Validate a code diff — check that the modernised code compiles
    (syntax check only, does not require a full Maven/Gradle build).

    Args:
        original_code:   The original Java source code.
        modernised_code: The proposed modernised code.

    Returns:
        {
          "status":  "valid" | "invalid",
          "diff":    str  – unified diff,
          "issues":  [str]
        }
    """
    issues = []

    # Basic structural checks
    orig_class_count  = original_code.count("class ")
    mod_class_count   = modernised_code.count("class ")
    orig_brace_balance = original_code.count("{") - original_code.count("}")
    mod_brace_balance  = modernised_code.count("{") - modernised_code.count("}")

    if orig_class_count != mod_class_count:
        issues.append(
            f"Class count mismatch: original={orig_class_count}, modernised={mod_class_count}"
        )
    if orig_brace_balance != mod_brace_balance:
        issues.append(
            f"Unbalanced braces: original balance={orig_brace_balance}, "
            f"modernised balance={mod_brace_balance}"
        )
    if modernised_code.strip() == "":
        issues.append("Modernised code is empty.")

    # Generate unified diff
    diff = _generate_diff(original_code, modernised_code)

    return {
        "status": "invalid" if issues else "valid",
        "diff":   diff,
        "issues": issues,
    }


def create_pull_request(
    repo_owner: str,
    repo_name: str,
    base_branch: str,
    changes: list[dict],
    project_id: str = "",
) -> dict:
    """
    Create a GitHub Pull Request with the modernised file changes.

    Args:
        repo_owner:   GitHub repository owner (org or user).
        repo_name:    Repository name.
        base_branch:  Target branch (e.g. "main" or "develop").
        changes:      List of dicts:
                      [{"file_path": str, "modernised_code": str,
                        "pattern_id": str, "explanation": str}, ...]
        project_id:   GCP project ID (for PR description).

    Returns:
        {
          "status":    "success" | "error",
          "pr_url":    str,
          "pr_number": int,
          "branch":    str
        }
    """
    if not GITHUB_TOKEN:
        return {
            "status":  "error",
            "message": "GITHUB_TOKEN environment variable not set.",
        }
    if not changes:
        return {"status": "error", "message": "No changes to commit."}

    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept":        "application/vnd.github.v3+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    base_url = f"{GITHUB_API_URL}/repos/{repo_owner}/{repo_name}"

    try:
        # 1. Get base branch SHA
        ref_resp = requests.get(f"{base_url}/git/ref/heads/{base_branch}", headers=headers)
        ref_resp.raise_for_status()
        base_sha = ref_resp.json()["object"]["sha"]

        # 2. Create new branch
        new_branch = f"srao/java-modernization-{base_sha[:7]}"
        branch_payload = {"ref": f"refs/heads/{new_branch}", "sha": base_sha}
        br_resp = requests.post(f"{base_url}/git/refs", json=branch_payload, headers=headers)
        br_resp.raise_for_status()

        # 3. Commit each changed file
        for change in changes:
            _commit_file(
                base_url=base_url,
                headers=headers,
                branch=new_branch,
                file_path=change["file_path"],
                content=change["modernised_code"],
                message=f"[SRAO] Modernise {change['file_path']}: {change['pattern_id']}",
            )

        # 4. Build PR body
        change_details = "\n".join(
            f"- **`{c['file_path']}`** — {c.get('explanation', c['pattern_id'])}"
            for c in changes
        )
        patterns = list({c["pattern_id"] for c in changes})

        pr_body = PR_BODY_TEMPLATE.format(
            file_count=len(changes),
            pattern_list=", ".join(patterns),
            change_details=change_details,
            project_id=project_id,
        )

        # 5. Open Pull Request
        pr_payload = {
            "title": PR_TITLE_TEMPLATE.format(file_count=len(changes)),
            "body":  pr_body,
            "head":  new_branch,
            "base":  base_branch,
        }
        pr_resp = requests.post(f"{base_url}/pulls", json=pr_payload, headers=headers)
        pr_resp.raise_for_status()
        pr_data = pr_resp.json()

        logger.info("PR created: %s", pr_data["html_url"])
        return {
            "status":    "success",
            "pr_url":    pr_data["html_url"],
            "pr_number": pr_data["number"],
            "branch":    new_branch,
        }

    except requests.HTTPError as exc:
        return {"status": "error", "message": f"GitHub API error: {exc.response.text}"}
    except Exception as exc:
        logger.exception("Unexpected error creating PR")
        return {"status": "error", "message": str(exc)}


# ── Helpers ───────────────────────────────────────────────────────────────────

def _generate_diff(original: str, modernised: str) -> str:
    """Generate a unified diff between two code strings."""
    with tempfile.NamedTemporaryFile("w", suffix=".java", delete=False) as f1, \
         tempfile.NamedTemporaryFile("w", suffix=".java", delete=False) as f2:
        f1.write(original)
        f2.write(modernised)
        f1_name, f2_name = f1.name, f2.name

    result = subprocess.run(
        ["diff", "-u", "--label", "original", "--label", "modernised", f1_name, f2_name],
        capture_output=True, text=True,
    )
    Path(f1_name).unlink(missing_ok=True)
    Path(f2_name).unlink(missing_ok=True)
    return result.stdout


def _commit_file(
    base_url: str,
    headers: dict,
    branch: str,
    file_path: str,
    content: str,
    message: str,
) -> None:
    """Create or update a file in a GitHub repository via the Contents API."""
    import base64

    # Check if file exists (to get its SHA for update)
    get_resp = requests.get(
        f"{base_url}/contents/{file_path}",
        params={"ref": branch},
        headers=headers,
    )
    existing_sha = get_resp.json().get("sha") if get_resp.status_code == 200 else None

    payload: dict = {
        "message": message,
        "content": base64.b64encode(content.encode()).decode(),
        "branch":  branch,
    }
    if existing_sha:
        payload["sha"] = existing_sha

    put_resp = requests.put(
        f"{base_url}/contents/{file_path}", json=payload, headers=headers
    )
    put_resp.raise_for_status()
